[impl] Horizontal pager (carousels)
Okura-JCH/Okura pull request #37
Opened 2024-03-19 20:38 UTC by soleil-colza

ライブラリなしで実装したぜ！ﾊﾟﾜｰ

2024-03-19 23:36 UTC, k-taro56 commented on build.gradle.kts
> +}
改行追加しててえらい

2024-03-19 23:38 UTC, k-taro56 commented on .idea/misc.xml
> -<?xml version="1.0" encoding="UTF-8"?>
xml の宣言消えてる

2024-03-19 23:39 UTC, k-taro56 requested changes
いっぱい寝ることを約束してくれないからだめ！

2024-03-20 07:30 UTC, soleil-colza commented on build.gradle.kts
> +}
ﾜｰｲ

2024-03-20 07:30 UTC, soleil-colza commented on .idea/misc.xml
> -<?xml version="1.0" encoding="UTF-8"?>
ｲﾗﾅｲ

2024-03-20 08:28 UTC, soleil-colza commented
> いっぱい寝ることを約束してくれないからだめ！

ねたもん〜

2024-03-20 08:33 UTC, k-taro56 approved these changes

2024-03-20 08:33 UTC, merged